# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: sysuuid 0.0.8 ruby lib
# stub: ext/extconf.rb

Gem::Specification.new do |s|
  s.name = "sysuuid"
  s.version = "0.0.8"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["David Turnbull"]
  s.date = "2015-02-03"
  s.description = "      sysuuid # => BBC4937C-344F-47C5-AA36-E19CC070DBCC\n"
  s.email = "dsturnbull@me.com"
  s.extensions = ["ext/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README"
  ]
  s.files = [
    "Rakefile",
    "ext/extconf.rb",
    "ext/sysuuid.c"
  ]
  s.homepage = "http://github.com/dsturnbull/sysuuid"
  s.rubygems_version = "2.4.5"
  s.summary = "uses uuid.h for fast uuid generation"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<should_be_faster>, [">= 0"])
    else
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<should_be_faster>, [">= 0"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<should_be_faster>, [">= 0"])
  end
end

